# The value of AppId uniquely identifies this application.
# Do not use the same AppId value in installers for other applications.
app_id: c5f91783-dd46-4489-9244-4121657875fb
publisher: lilgeek.360
publisher_url: https://github.com/LiL-GeeK
display_name: Minesweeper
create_desktop_icon: true
# See: https://jrsoftware.org/ishelp/index.php?topic=setup_defaultdirname
# install_dir_name: "D:\\HELLO-WORLD"
# This path is relative to the root directory of your project; The format of icon file must be ico, can not be png or others
# setup_icon_file: windows\runner\resources\app_icon.ico
locales:
  - en